[build]
  publish = "."

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

[functions."reporte-diario"]
  schedule = "0 14 * * *"

[functions."reporte-semanal"]
  schedule = "0 14 * * 1"
