[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[functions."reporte-diario"]
  schedule = "0 14 * * *"

[functions."reporte-semanal"]
  schedule = "0 14 * * 1"
